global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "fastapi-app"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
